import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddTaskModal from "@/components/AddTaskModal";
import UpdateTaskModal from "@/components/UpdateTaskModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <AddTaskModal />
        <UpdateTaskModal/>
      </body>
    </html>
  );
}
